mod_blog/models.py
from sqlalchemy import Column,Integer,String, Text, Table, ForeignKey

from app import db

posts_categories = Table('posts_categories', db.metadata,
    Column('post_id', Integer, ForeignKey('posts.id', ondelete='cascade'), primary_key=True),
    Column('category_id', Integer, ForeignKey('categories.id', ondelete='cascade'), primary_key=True)
)

class Category(db.Model):
    __tablename__ = 'categories'
    id = Column(Integer,primary_key=True)
    name = Column(String(128),nullable=False, unique=True)
    description = Column(String(256),nullable=True, unique=False)
    slug = Column(String(128),nullable=False, unique=True)
    posts = db.relationship("Post", secondary=posts_categories, back_populates="categories")


class Post(db.Model):
    __tablename__ = 'posts'
    id = Column(Integer,primary_key=True)
    title = Column(String(128),nullable=False, unique=True)
    summary = Column(String(256),nullable=True, unique=False)
    content = Column(Text,nullable=False, unique=False)
    slug = Column(String(128),nullable=False, unique=True)
    categories = db.relationship("Category", secondary=posts_categories, back_populates="posts")

mod_users/models.py
from sqlalchemy import Integer, String, Column
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


class User(db.Model):
    __tablename__ = 'users'  # --->changing table name
    id = Column(Integer(), primary_key=True)
    email = Column(String(256), nullable=False, unique=True)
    password = Column(String(128), nullable=False, unique=False)
    role = Column(Integer(), nullable=False, default=0)
    full_name = Column(String(256), nullable=True, unique=False)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password,password)
    
    def is_admin(self):
        return self.role == 1

mod_blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextField,TextAreaField
from wtforms.validators import DataRequired


class CreatePostForm(FlaskForm):
    title = TextField(validators = [DataRequired()])
    summary = TextAreaField()
    content = TextAreaField(validators = [DataRequired()])
    slug = TextField(validators = [DataRequired()])

mod_users/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.html5 import EmailField
from wtforms import PasswordField,StringField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    email = EmailField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])


class Register_Form(FlaskForm):
    full_name = StringField()
    email = EmailField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])
    confirm_password = PasswordField(validators=[DataRequired()])

app.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from config import Development

app = Flask(__name__)
app.config.from_object(Development)


db = SQLAlchemy(app)
migrate = Migrate(app, db)

from views import *
from mod_admin import admin
from mod_users import users
from mod_blog import blog

app.register_blueprint(admin)
app.register_blueprint(users)
app.register_blueprint(blog)

mod_admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__, url_prefix='/admin/')

from .views import *

mod_admin/views.py
from app import db
from flask import (abort, flash, redirect, render_template, request, session,
                   url_for)
from sqlalchemy.exc import IntegrityError
from mod_blog.forms import CreatePostForm
from mod_blog.models import Post
from mod_users.forms import LoginForm
from mod_users.models import User

from . import admin
from .utils import admin_only_view


@admin.route('/')
@admin_only_view
def index():
    return render_template('admin/index.html')


@admin.route('/login/', methods = ['GET' , 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        # print(f'Form is validated!? {form.validate_on_submit()}')
        if not form.validate_on_submit():
            abort(400)
        user = User.query.filter(User.email == form.email.data).first()
        # user = User.query.filter(User.email.ilike(f'{form.email.data}')).first()
        # print(user)
        if not user:
            flash('Incorrect Email', category='Error')
            return render_template('admin/login.html', form = form) # ,title = 'Admin Login'
        if not user.check_password(form.password.data):
            flash('Incorrect Password', category='Error')
            return render_template('admin/login.html', form = form) # ,title = 'Admin Login'
        # if not user.is_admin():
        #     flash('Sorry! You are not admin', category='Warning')
        #     return render_template('admin/login.html', form = form) # ,title = 'Admin Login'
        session['email'] = user.email
        session['user_id'] = user.id
        session['role'] = user.role
        # print(session)
        return redirect(url_for('admin.index'))
    if session.get('role') == 1:
        return redirect(url_for('admin.index'))


    # session['name'] = 'Davood'
    # session.clear()
    # print(session.get('name'))
    # print(session)
    return render_template('admin/login.html', form = form) # ,title = 'Admin Login'

@admin.route('/logout/', methods = ['GET'])
@admin_only_view
def logout():
    session.clear()
    flash('You logged out successfuly!','Warning')
    return redirect(url_for('admin.login'))

@admin.route('/posts/new', methods = ['GET' , 'POST'])
@admin_only_view
def create_post():
    form = CreatePostForm(request.form)
    if request.method == 'POST':
        if not form.validate_on_submit():
            return 'not validate'
        new_post = Post()
        new_post.title = form.title.data
        new_post.content = form.content.data
        new_post.slug = form.slug.data
        new_post.summary = form.summary.data
        try:
            db.session.add(new_post)
            db.session.commit()
            flash('Post created!')
            return redirect(url_for('admin.index'))
        # except Exception as e:
        except IntegrityError:
            db.session.rollback()

    return render_template('admin/create_post.html', form = form)

mod_blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog',__name__,url_prefix='/blog/')


from . import models

mod_users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__, url_prefix='/users/')

from mod_users.models import User
from . import views

mod_users/views.py
from flask import request, render_template, flash
from sqlalchemy.exc import IntegrityError
from app import db
from . import users
from .forms import Register_Form
from .models import User


@users.route('/register/', methods = ['GET' , 'POST'])
def register():
    form = Register_Form(request.form)
    if request.method == 'POST':
        if not form.validate_on_submit():
            return render_template('users/register.html', form=form)
        if not form.password.data == form.confirm_password.data:
            error_msg = 'Password and Confirm Password does not match!'
            form.confirm_password.errors.append(error_msg)
        # اگر فیلدهای بیشتری برای یونیک بودن وجود داشته باشد نمی شود که از ترای استفاده کرد
        # و باید به شکل زیر اول یه کوری زد و سرچ کرد
        # find_user = User.query.filter(User.email.ilike(form.email.data)).first()
        # if find_user:
        #     flash('Email is in use.','Error')
        #     return render_template('users/register.html', form=form)
        new_user = User()
        new_user.full_name = form.full_name.data
        new_user.email = form.email.data
        new_user.set_password(form.password.data)
        try:
            db.session.add(new_user)
            db.session.commit()
            flash('Your account was create successfully.','success')
        # except Exception
        except IntegrityError:
            db.session.rollback()
            flash('Email is in use.','Error')
    return render_template('users/register.html', form=form)

views.py
from app import app
from flask import render_template


@app.route('/')
def hello_world():
    return render_template('index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <title>{{ title }}</title> -->
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css">
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block title %}Home Page{% endblock %}


{% block content %}
<h1>Home Page | Flask Blog</h1>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<h1>Please fill the form :</h1>
<form action="{{ url_for('users.register') }}" method="POST">
    {% with messages = get_flashed_messages(True) %}
        {% if messages %}
        <div class="row">
            <ul class=flashes>
                {% for message in messages %}
                <div class="card {{ message[0] }}">
                    <li>{{ message[0] }} : {{ message[1] }}</li>
                </div>
                {% endfor %}
            </ul>
        </div>
      {% endif %}
    {% endwith %}
    {{ form.hidden_tag() }}
    Full Name : {{ form.full_name }} <br/>
    {% if form.full_name.errors %}
    <ul>
        {% for error in form.full_name.errors %}
         <li>{{ error }}</li>
       {% endfor %}
    </ul>
    {% endif %}
    Email : {{ form.email }} <br/>
    {% if form.email.errors %}
    <ul>
        {% for error in form.email.errors %}
         <li>{{ error }}</li>
       {% endfor %}
    </ul>
    {% endif %}
    Password : {{ form.password }} <br/>
    {% if form.password.errors %}
    <ul>
        {% for error in form.password.errors %}
         <li>{{ error }}</li>
       {% endfor %}
    </ul>
    {% endif %}
    Confirm Password : {{ form.confirm_password }} <br/>
    {% if form.confirm_password.errors %}
    <ul>
        {% for error in form.confirm_password.errors %}
         <li>{{ error }}</li>
       {% endfor %}
    </ul>
    {% endif %}    <input type='submit' value ='Register'>
</form>
{% endblock content %}